//Testar as requisições - Schema Cardapio
//Bye, Bye Postman :) (Mas claro, ainda dá para utilizá-lo se preferir)
//Instale a extensão REST Client no Visual Studio Code para conseguir utilizar este recurso

@baseUrl = http://localhost:4000
@id = 604787c65e1a4608df2b782a
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjA0NzZkMWE0ZDk0MDgwNDUwM2M5NTk4In0sImlhdCI6MTYxNTI5MzcyMiwiZXhwIjoxNjE1MzI5NzIyfQ.zLK2BHsSXDvCOoIfW_rXTej5pYxD_aSRV5q473iPiOc

###
// GET Todos os cardapios
GET {{baseUrl}}/cardapios
Content-Type: application/json

###
// GET Retorna um cardapio pelo ID
GET {{baseUrl}}/cardapios/{{id}}
Content-Type: application/json

###
// POST Novo Cardapio
POST {{baseUrl}}/cardapios
Content-Type: application/json

{
    "nome": "Parmegiana de Filé Mignon",
    "status": "ativo",
    "foto": "",
    "descricao": "Filé mignon à milanesa empanado com tempero da casa, servido no molho de tomate natural coberto com queijo mussarela.",  
    "preco": 39.90,
    "calorias": 1200,
    "restaurante": "6059fc0f45da2a0853f13a14"
}

###
// POST Novo Cardapio
POST {{baseUrl}}/cardapios
Content-Type: application/json

{
    "nome": "Parmegiana de Frango",
    "status": "ativo",
    "foto": "",
    "descricao": "Filé de peito de frango à milanesa empanado com tempero da casa, servido no molho de tomate natural coberto com queijo mussarela.",  
    "preco": 29.90,
    "calorias": 980,
    "restaurante": "6059fc0f45da2a0853f13a14"
}

###
// DELETE Remove Cardapio
DELETE {{baseUrl}}/cardapios/{{id}}
Content-Type: application/json
access-token: {{token}}

###
// PUT Edita Cardapio
PUT {{baseUrl}}/cardapios
Content-Type: application/json
access-token: {{token}}

{
    "_id": "60477975c0e5740660e4074bd",
    "codigo": "1234567890124",
    "nome": "Feijão Preto",  
    "preco": 9.90,
    "validade": "2021-12-13",
    "descricao": "Feijão Preto Tipo 2 marca Camil", 
    "inativo": false,
    "unidade": "Kg",
    "grupo": "604786f883fbe0089651095a"
}
